Enable multiple anchors and to top single anchor
Manotomo-Alliance-Support-Squad/aqua-sweet-dreams pull request #22
Opened 2021-06-08 18:01 UTC by Lr-Jim

Closes #18

2021-06-09 16:54 UTC, zapplecat commented
I can't really see the TOP button when I'm all the way down.
![image](https://user-images.githubusercontent.com/6146988/121396426-fb73cb00-c918-11eb-8c9b-628b30f26ff6.png)

Maybe forgo the TOP button and add a top section to the multi-anchor?

2021-06-09 16:55 UTC, zapplecat commented on frontend/src/assets/icons/anchorIcon.svg
> +  <title>Layer 1</title>
This is showing up as a alt-text when hovering over the anchor. I'd remove or change it to `page-anchor`. Better yet, to support accessibility, we should have the alt-text that have the name of the anchored section.

2021-06-09 19:04 UTC, zapplecat approved these changes
Left some minor comments, overall lgtm

2021-06-09 19:04 UTC, zapplecat commented on frontend/src/App.tsx
> +                    svgIcon: AnchorBotan, //TODO: replace this with aqua onion
Just leaving a comment here to make sure we don't forget to replace the icon. Not sure if we want to merge before/after.

2021-06-09 19:04 UTC, zapplecat commented on frontend/src/components/comboSection/comboSection.tsx
> +                <div key={id} className="card-section">
Thanks for fixing these. I kept seeing the console error but smol brain hasn't processed it was coming from here.

2021-06-09 19:04 UTC, zapplecat commented on frontend/src/pages/home/home.tsx
> +        text: "Message",
nit: `Messages` instead of message.

2021-06-09 22:20 UTC, DuongTyler commented
I was thinking we could make it fade in and out transparently using :hover in the CSS. I think it might look a little better that way

2021-06-09 22:25 UTC, DuongTyler commented
Also, it doesn't look good on mobile phones. We might want to consider making a special rule to hide it on phone layouts in the CSS

2021-06-09 22:26 UTC, DuongTyler commented
![image](https://user-images.githubusercontent.com/38551592/121437347-04739500-c937-11eb-9ed5-80e57035ae97.png)
I didn't notice that this was a thing, perhaps we should make it a button instead? also I didn't exactly know what clicking this would do.

2021-06-09 22:27 UTC, DuongTyler requested changes
see above comments

2021-06-10 01:44 UTC, Lr-Jim commented
> ![image](https://user-images.githubusercontent.com/38551592/121437347-04739500-c937-11eb-9ed5-80e57035ae97.png)
> I didn't notice that this was a thing, perhaps we should make it look more like a button with a circular colored background instead? also I didn't exactly know what clicking this would do.

I just left it as a placeholder until we get the icon for it but yeah I will update it

2021-06-10 02:19 UTC, Lr-Jim commented
> see above comments

All are updated in description

2021-06-10 07:21 UTC, DuongTyler commented
I think it might be better to have the visibility of the "jump to top" button also be transparent until hovered over.
Also we might as well just some material design arrow or button instead. Makes things simple to understand the function of

2021-06-10 07:23 UTC, DuongTyler commented
![image](https://user-images.githubusercontent.com/38551592/121482336-eda66000-c981-11eb-8a70-abf35b7ab06f.png)
also Minor nit: sometimes the position of the sidebar doesn't update on the page

2021-06-10 22:13 UTC, DuongTyler approved these changes
lgtm, but I would change the anchor icon to an up arrow or something

2021-06-10 22:13 UTC, DuongTyler commented
by that I mean the jump to top button

2021-06-10 22:24 UTC, zapplecat commented
> lgtm, but I would change the anchor icon to an up arrow or something

lol, do a reverse anchor to make it look like it's pointing it. (But really, don't, it would probably look terrible.)

2021-06-11 02:08 UTC, Lr-Jim commented
> > lgtm, but I would change the anchor icon to an up arrow or something
> 
> lol, do a reverse anchor to make it look like it's pointing it. (But really, don't, it would probably look terrible.)

lol I will create a new svg icon for it

2021-06-18 23:23 UTC, merged