Add game section
Manotomo-Alliance-Support-Squad/aqua-sweet-dreams pull request #33
Opened 2021-06-20 10:59 UTC by Lr-Jim

2021-06-21 02:29 UTC, DuongTyler requested changes
we might want to make the game card take up the entirety of the horizontal space since there isn't going to be more than one for this site. Also, it might be better to have the title and description both be on the bottom of the card, having title + buttons on top and description on bottom seems jarring to me...

2021-06-21 02:30 UTC, DuongTyler commented
or perhaps we can just make a dedicated section of the page and hard-code the stuff in there instead of using the gamesection

2021-06-24 03:09 UTC, Lr-Jim commented
@DuongTyler can you review this again?

2021-06-24 03:16 UTC, DuongTyler commented
Thanks for the reminder, will check it out once I get home 👍

2021-06-24 03:38 UTC, zapplecat commented on frontend/src/components/gallery/artworkCard/artworkImage.tsx
> -        console.log(this.getImage())
nice catch.

2021-06-24 03:38 UTC, zapplecat commented on frontend/src/models/achor.ts
>      href: string;
I just noticed... The name of this file is `achor` and not `anchor`

2021-06-24 04:05 UTC, DuongTyler approved these changes
This looks really goooood!

2021-06-24 04:31 UTC, DuongTyler commented
ah, make sure you bring the changes over to the mass-backend repo, we are gonna retire the backend folder here

2021-06-24 12:41 UTC, merged